services:
  mysql:
    image: mysql:8.4
    container_name: trekking-ecommerce-mysql
    environment:
      MYSQL_DATABASE: trekking_ecommerce
      MYSQL_ROOT_PASSWORD: 12345
      TZ: America/Argentina/Buenos_Aires
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:

